---
actionlint: [internal/skipfiles]
adrs: [cargo]
ansible: [internal/skipfiles, uv]
bash-exec: []
bencher: []
biome-bun: [bun, internal/skipfiles]
biome-npm-fnm: [internal/skipfiles, npm-fnm]
biome-npm-nvm: [internal/skipfiles, npm-nvm]
biome-pnpm-fnm: [internal/skipfiles, pnpm-fnm]
biome-pnpm-nvm: [internal/skipfiles, pnpm-nvm]
biome-yarn-fnm: [internal/skipfiles, yarn-fnm]
biome-yarn-nvm: [internal/skipfiles, yarn-nvm]
bruno-bun: [bun]
bruno-npm-fnm: [npm-fnm]
bruno-npm-nvm: [npm-nvm]
bruno-pnpm-fnm: [pnpm-fnm]
bruno-pnpm-nvm: [pnpm-nvm]
bruno-yarn-fnm: [yarn-fnm]
bruno-yarn-nvm: [yarn-nvm]
buf: [internal/skipfiles]
bun: []
cargo: [internal/skipfiles]
corepack-fnm: [fnm]
corepack-nvm: [nvm]
depcheck-bun: [bun]
depcheck-npm-fnm: [npm-fnm]
depcheck-npm-nvm: [npm-nvm]
depcheck-pnpm-fnm: [pnpm-fnm]
depcheck-pnpm-nvm: [pnpm-nvm]
depcheck-yarn-fnm: [yarn-fnm]
depcheck-yarn-nvm: [yarn-nvm]
djlint: [uv]
docker: []
dotenv-linter: [cargo, internal/skipfiles]
eslint-bun: [bun]
eslint-npm-fnm: [npm-fnm]
eslint-npm-nvm: [npm-nvm]
eslint-pnpm-fnm: [pnpm-fnm]
eslint-pnpm-nvm: [pnpm-nvm]
eslint-yarn-fnm: [yarn-fnm]
eslint-yarn-nvm: [yarn-nvm]
fnm: []
gh: [jq]
git: [gh]
go: [internal/skipfiles]
hadolint: [internal/skipfiles]
htmlhint-npm-fnm: [npm-fnm]
htmlhint-npm-nvm: [npm-nvm]
htmlhint-pnpm-fnm: [pnpm-fnm]
htmlhint-pnpm-nvm: [pnpm-nvm]
internal/skipfiles: []
jq: []
jsonlint: [internal/skipfiles, uv]
knip-bun: [bun, internal/skipfiles]
knip-npm-fnm: [internal/skipfiles, npm-fnm]
knip-npm-nvm: [internal/skipfiles, npm-nvm]
knip-pnpm-fnm: [internal/skipfiles, pnpm-fnm]
knip-pnpm-nvm: [internal/skipfiles, pnpm-nvm]
knip-yarn-fnm: [internal/skipfiles, yarn-fnm]
knip-yarn-nvm: [internal/skipfiles, yarn-nvm]
npm-fnm: [corepack-fnm, fnm]
npm-nvm: [corepack-nvm, nvm]
nvm: []
pnpm-fnm: [corepack-fnm, fnm]
pnpm-nvm: [corepack-nvm, nvm]
prettier-bun: [bun]
prettier-npm-fnm: [npm-fnm]
prettier-npm-nvm: [npm-nvm]
prettier-pnpm-fnm: [pnpm-fnm]
prettier-pnpm-nvm: [pnpm-nvm]
prettier-yarn-fnm: [yarn-fnm]
prettier-yarn-nvm: [yarn-nvm]
proto: [go]
protolint: [go, internal/skipfiles]
python: [uv]
rumdl: [uv]
shellcheck: [internal/skipfiles]
shfmt: [go, internal/skipfiles]
spectral-npm-fnm: [npm-fnm]
spectral-npm-nvm: [npm-nvm]
spectral-pnpm-fnm: [pnpm-fnm]
spectral-pnpm-nvm: [pnpm-nvm]
sqlfluff: [internal/skipfiles, uv]
staticcheck: [go]
stylelint-bun: [bun]
stylelint-npm-fnm: [npm-fnm]
stylelint-npm-nvm: [npm-nvm]
stylelint-pnpm-fnm: [pnpm-fnm]
stylelint-pnpm-nvm: [pnpm-nvm]
stylelint-yarn-fnm: [yarn-fnm]
stylelint-yarn-nvm: [yarn-nvm]
typescript-bun: [bun]
typescript-npm-fnm: [npm-fnm]
typescript-npm-nvm: [npm-nvm]
typescript-pnpm-fnm: [pnpm-fnm]
typescript-pnpm-nvm: [pnpm-nvm]
typescript-yarn-fnm: [yarn-fnm]
typescript-yarn-nvm: [yarn-nvm]
uv: []
vault: [jq]
yamllint: [internal/skipfiles, uv]
yarn-fnm: [corepack-fnm, fnm]
yarn-nvm: [corepack-nvm, nvm]
zizmor: [internal/skipfiles]
