---
actionlint: []
ansible: [uv]
biome-bun: [bun]
biome-npm-fnm: [npm-fnm]
biome-npm-nvm: [npm-nvm]
biome-pnpm-fnm: [pnpm-fnm]
biome-pnpm-nvm: [pnpm-nvm]
biome-yarn-fnm: [yarn-fnm]
biome-yarn-nvm: [yarn-nvm]
bruno-bun: [bun]
bruno-npm-fnm: [npm-fnm]
bruno-npm-nvm: [npm-nvm]
bruno-pnpm-fnm: [pnpm-fnm]
bruno-pnpm-nvm: [pnpm-nvm]
bruno-yarn-fnm: [yarn-fnm]
bruno-yarn-nvm: [yarn-nvm]
buf: []
bun: []
corepack-fnm: [fnm]
corepack-nvm: [nvm]
depcheck-bun: [bun]
depcheck-npm-fnm: [npm-fnm]
depcheck-npm-nvm: [npm-nvm]
depcheck-pnpm-fnm: [pnpm-fnm]
depcheck-pnpm-nvm: [pnpm-nvm]
depcheck-yarn-fnm: [yarn-fnm]
depcheck-yarn-nvm: [yarn-nvm]
docker: []
eslint-bun: [bun]
eslint-npm-fnm: [npm-fnm]
eslint-npm-nvm: [npm-nvm]
eslint-pnpm-fnm: [pnpm-fnm]
eslint-pnpm-nvm: [pnpm-nvm]
eslint-yarn-fnm: [yarn-fnm]
eslint-yarn-nvm: [yarn-nvm]
fnm: []
gh: [jq]
git: [gh]
go: []
hadolint: []
jq: []
knip-bun: [bun]
knip-npm-fnm: [npm-fnm]
knip-npm-nvm: [npm-nvm]
knip-pnpm-fnm: [pnpm-fnm]
knip-pnpm-nvm: [pnpm-nvm]
knip-yarn-fnm: [yarn-fnm]
knip-yarn-nvm: [yarn-nvm]
npm-fnm: [corepack-fnm, fnm]
npm-nvm: [corepack-nvm, nvm]
nvm: []
pnpm-fnm: [corepack-fnm, fnm]
pnpm-nvm: [corepack-nvm, nvm]
prettier-bun: [bun]
prettier-npm-fnm: [npm-fnm]
prettier-npm-nvm: [npm-nvm]
prettier-pnpm-fnm: [pnpm-fnm]
prettier-pnpm-nvm: [pnpm-nvm]
prettier-yarn-fnm: [yarn-fnm]
prettier-yarn-nvm: [yarn-nvm]
proto: [go]
python: [uv]
shellcheck: []
sqlfluff: [uv]
staticcheck: [go]
stylelint-bun: [bun]
stylelint-npm-fnm: [npm-fnm]
stylelint-npm-nvm: [npm-nvm]
stylelint-pnpm-fnm: [pnpm-fnm]
stylelint-pnpm-nvm: [pnpm-nvm]
stylelint-yarn-fnm: [yarn-fnm]
stylelint-yarn-nvm: [yarn-nvm]
typescript-bun: [bun]
typescript-npm-fnm: [npm-fnm]
typescript-npm-nvm: [npm-nvm]
typescript-pnpm-fnm: [pnpm-fnm]
typescript-pnpm-nvm: [pnpm-nvm]
typescript-yarn-fnm: [yarn-fnm]
typescript-yarn-nvm: [yarn-nvm]
uv: []
vault: [jq]
yamllint: [uv]
yarn-fnm: [corepack-fnm, fnm]
yarn-nvm: [corepack-nvm, nvm]
zizmor: []
